// src/components/NewIdeaDialog.tsx
import * as React from 'react';
import { useState } from 'react';
import type { Idea } from '~/lib/github';
import { Button } from './ui/button';
import { Dialog } from './ui/dialog';

interface NewIdeaDialogProps {
  open: boolean;
  onClose: () => void;
}

const TITLE_MIN = 10;
const TITLE_MAX = 300;
const BODY_MIN = 30;
const BODY_MAX = 10000;

const inputClass = (dirty: boolean): string =>
  `input ${dirty ? 'input-dirty' : ''}`;
const textareaClass = (dirty: boolean): string =>
  `input textarea min-h-40 resize-y ${dirty ? 'input-dirty' : ''}`;

export function NewIdeaDialog({ open, onClose }: NewIdeaDialogProps): React.ReactElement {
  const [title, setTitle] = useState('');
  const [body, setBody] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const titleLen = title.trim().length;
  const bodyLen = body.trim().length;
  const titleValid = titleLen >= TITLE_MIN && titleLen <= TITLE_MAX;
  const bodyValid = bodyLen >= BODY_MIN && bodyLen <= BODY_MAX;
  const canSubmit = titleValid && bodyValid && !submitting;

  function reset(): void {
    setTitle('');
    setBody('');
    setError(null);
    setSubmitting(false);
  }

  function handleClose(): void {
    if (submitting) return;
    reset();
    onClose();
  }

  async function handleSubmit(e: React.FormEvent<HTMLFormElement> | React.MouseEvent<HTMLButtonElement>): Promise<void> {
    e.preventDefault();
    if (!canSubmit) return;
    setSubmitting(true);
    setError(null);
    try {
      const csrfToken = window.__ideasCsrfToken ?? '';
      const res = await fetch('/api/create-idea', {
        method: 'POST',
        credentials: 'same-origin',
        headers: {
          'content-type': 'application/json',
          'x-csrf-token': csrfToken,
        },
        body: JSON.stringify({ title: title.trim(), body: body.trim() }),
      });
      if (res.status === 401) {
        setError('Session expired. Please sign in again.');
        return;
      }
      if (!res.ok) {
        const text = await res.text();
        setError(text || `HTTP ${res.status}`);
        return;
      }
      const idea = (await res.json()) as Idea;
      window.dispatchEvent(new CustomEvent('idea:created', { detail: idea }));
      reset();
      onClose();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      title="New idea"
      description="Post a new idea to GitHub Discussions. Title and body are required."
    >
      <form onSubmit={(e) => void handleSubmit(e)} className="flex flex-col gap-3">
        <div>
          <div className="mb-1 flex items-center justify-between">
            <label htmlFor="new-idea-title" className="text-xs font-bold uppercase tracking-widest text-neutral-300">
              Title
            </label>
            <span
              className={`font-mono text-[10px] ${
                titleValid ? 'text-neutral-500' : 'text-warning'
              }`}
            >
              {titleLen}/{TITLE_MAX}
            </span>
          </div>
          <input
            id="new-idea-title"
            type="text"
            className={inputClass(title.length > 0)}
            placeholder="A short, descriptive title"
            value={title}
            maxLength={TITLE_MAX}
            disabled={submitting}
            onChange={(e) => setTitle(e.target.value)}
            required
          />
        </div>

        <div>
          <div className="mb-1 flex items-center justify-between">
            <label htmlFor="new-idea-body" className="text-xs font-bold uppercase tracking-widest text-neutral-300">
              Body
            </label>
            <span
              className={`font-mono text-[10px] ${
                bodyValid ? 'text-neutral-500' : 'text-warning'
              }`}
            >
              {bodyLen}/{BODY_MAX}
            </span>
          </div>
          <textarea
            id="new-idea-body"
            className={textareaClass(body.length > 0)}
            placeholder="Describe the idea: what it does, why it's useful, any details that help others evaluate it. Markdown supported."
            value={body}
            maxLength={BODY_MAX}
            disabled={submitting}
            onChange={(e) => setBody(e.target.value)}
            rows={8}
            required
          />
          <p className="mt-1 text-[10px] text-neutral-600">
            Posted to GitHub Discussions in the “Ideas” category as your account.
          </p>
        </div>

        {error && (
          <div className="rounded-sm border border-error/50 bg-error/10 px-3 py-2 text-xs text-error">
            {error}
          </div>
        )}

        <div className="mt-1 flex items-center justify-end gap-2">
          <Button variant="ghost" onClick={handleClose} disabled={submitting}>
            Cancel
          </Button>
          <Button
            type="submit"
            variant="highlighted"
            disabled={!canSubmit}
            onClick={(e) => void handleSubmit(e)}
          >
            {submitting ? 'Posting…' : 'Post idea'}
          </Button>
        </div>
      </form>
    </Dialog>
  );
}

// frontend/src/lib/components/NewIdeaDialog.svelte
<script lang="ts">
  import { createIdea, type Idea } from '$lib/api';

  export let open = false;
  export let csrfToken: string | null = null;
  export let onClose: () => void;
  export let onCreated: (idea: Idea) => void;

  let title = '';
  let body = '';
  let error = '';
  let submitting = false;

  const TITLE_MIN = 10;
  const TITLE_MAX = 300;
  const BODY_MIN = 30;
  const BODY_MAX = 10000;

  $: titleLen = title.trim().length;
  $: bodyLen = body.trim().length;
  $: canSubmit = Boolean(csrfToken) && titleLen >= TITLE_MIN && titleLen <= TITLE_MAX && bodyLen >= BODY_MIN && bodyLen <= BODY_MAX && !submitting;

  function reset() {
    title = '';
    body = '';
    error = '';
  }

  function close() {
    reset();
    onClose();
  }

  async function submit() {
    if (!canSubmit || !csrfToken) return;
    submitting = true;
    error = '';
    try {
      const idea = await createIdea(title.trim(), body.trim(), csrfToken);
      onCreated(idea);
      close();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Could not create idea.';
    } finally {
      submitting = false;
    }
  }
</script>

{#if open}
  <div class="modal-backdrop" role="presentation" on:click={close}></div>
  <div class="modal" role="dialog" aria-modal="true" aria-labelledby="new-idea-title">
    <header>
      <div>
        <h2 id="new-idea-title">New idea</h2>
        <p>Submit a local idea. Your GitHub account is used only for identity.</p>
      </div>
      <button class="icon-button" type="button" on:click={close} aria-label="Close">×</button>
    </header>

    <form on:submit|preventDefault={submit}>
      <label>
        <span>Title <small>{titleLen}/{TITLE_MAX}</small></span>
        <input class="input" bind:value={title} maxlength={TITLE_MAX} required placeholder="A short, descriptive title" />
      </label>
      <label>
        <span>Body <small>{bodyLen}/{BODY_MAX}</small></span>
        <textarea class="input textarea" bind:value={body} maxlength={BODY_MAX} required rows="8" placeholder="Describe what this should do and why it is useful."></textarea>
      </label>
      {#if error}<p class="error">{error}</p>{/if}
      <footer>
        <button class="button button-ghost" type="button" on:click={close}>Cancel</button>
        <button class="button button-highlighted" type="submit" disabled={!canSubmit}>{submitting ? 'Creating…' : 'Create idea'}</button>
      </footer>
    </form>
  </div>
{/if}
